// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ZZrHKZ6prTe5Vu0_N-7Z0S4KSkAOwKM',
    appId: '1:473922198316:web:a5584c91230d4372f62a89',
    messagingSenderId: '473922198316',
    projectId: 'fitness-1be6b',
    authDomain: 'fitness-1be6b.firebaseapp.com',
    storageBucket: 'fitness-1be6b.appspot.com',
    measurementId: 'G-78M03C3HXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcPFHcI42qyrX9Wd9M5bcyeIYSAgSIPLE',
    appId: '1:473922198316:android:ad2fd232f8050472f62a89',
    messagingSenderId: '473922198316',
    projectId: 'fitness-1be6b',
    storageBucket: 'fitness-1be6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfcz9ae7S1ViJdclTi9VIl-NI42ljXfog',
    appId: '1:473922198316:ios:a1f0f4c6d519f8e6f62a89',
    messagingSenderId: '473922198316',
    projectId: 'fitness-1be6b',
    storageBucket: 'fitness-1be6b.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfcz9ae7S1ViJdclTi9VIl-NI42ljXfog',
    appId: '1:473922198316:ios:a1f0f4c6d519f8e6f62a89',
    messagingSenderId: '473922198316',
    projectId: 'fitness-1be6b',
    storageBucket: 'fitness-1be6b.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-ZZrHKZ6prTe5Vu0_N-7Z0S4KSkAOwKM',
    appId: '1:473922198316:web:676dcb1d722f0a02f62a89',
    messagingSenderId: '473922198316',
    projectId: 'fitness-1be6b',
    authDomain: 'fitness-1be6b.firebaseapp.com',
    storageBucket: 'fitness-1be6b.appspot.com',
    measurementId: 'G-BGLCNMQ7JX',
  );
}
